version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017" # Expondo a porta do MongoDB para conexões externas
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: clinic # Define o banco de dados inicial a ser criado
    volumes:
      - mongo_data:/data/db # Volume persistente para os dados do MongoDB

volumes:
  mongo_data:
